### ISSUE TITLE
#0001 Change CONFIG_PHYS_OFFSET address

### ISSUE THREAD

**Issue by t0mm13b** [ZTE-BLADE/ZTE-BLADE-2.6.32#1]
Thought I'd help out point out a change or two based on modaco's forum...

As per http://android.modaco.com/content-page/328613/zte-blade-series-froyo-kernel-2-6-32-source-code/page/160/# comment 160..

also, the configuration located at http://android.modaco.com/content-page/328613/zte-blade-series-froyo-kernel-2-6-32-source-code/page/171/# (comment #171) (that's 3 configurations...)

Best regards

**Comment by t0mm13b** [comment]
http://android.modaco.com/index.php?act=attach&type=post&id=68353 <- configuration...

The problem is there's too many configurations so which is the correct one to simply amend the rom by replacing the kernel?

**Comment by ZTE-BLADE** [comment]
Thank you t0mm13b, I will add the patches soon :) (after we determine the best config)

I have added you as a collaborator so you have the option for  greater freedom with this repo :)

**Comment by Evilpaul** [comment]
It would be helpful if issues actually had useful names. The name of this issue is not useful as it gives no information about what the problem is.

I'd suggest renaming this issue something like "Change CONFIG_PHYS_OFFSET address" to cover the memory map issue, and open a 2nd issue for dealing with the config file.

**Comment by t0mm13b** [comment]
@EvilPaul: oh my apologies for a crappy title name of the issue.... sorry :(

**Comment by ZTE-BLADE** [comment]
Id rather have a non-descript issue title than it not to be listed at all :)

**Comment by Evilpaul** [comment]
I'd rather have the issues listed as well, it's just if you have to start fixing things but all the issues have a title like "some small bugfix" then it gets messy. Keeping everything nicely described from issue #1 will help in the long term.

**Comment by ZTE-BLADE** [comment]
The amended Kconfig has been uploaded and a separate issue has been made to determine the correct Kernel build file.

Closed
